# Generated by Django 3.2.9 on 2021-11-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_skills_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(default=1, max_length=3000),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.TextField(default=1, max_length=3000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
