# Generated by Django 3.2.9 on 2021-11-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_project_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.CharField(max_length=500),
        ),
    ]
