# Generated by Django 3.2.9 on 2021-11-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20211110_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='default.jpeg', null=True, upload_to='profile/'),
        ),
    ]
