# Generated by Django 3.2.9 on 2021-11-12 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='owner',
            new_name='profile',
        ),
    ]
